name: Generate snake animation

on:
  schedule: # executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output # Fazer o checkout diretamente no branch output

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move generated snake.svg to dist folder
        run: mv snake.svg dist/snake.svg

      - name: Verify snake.svg generation
        run: ls dist/snake.svg

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
